### ISSUE TITLE
Docs and examples seems to be offline

### ISSUE THREAD

**Issue by francescocretti** [d3plus/d3plus-text#128]
All links to docs and examples point to a 404 page.

e.g. https://d3plus.org/examples/d3plus-text/resizing-text/

**Comment by davelandry** [comment]
@francescocretti we just ported the majority of our chart examples to a new website format: https://d3plus.org/

We're still in the process of writing examples for the utility functions, like `TextBox`: https://github.com/d3plus/d3plus/issues/761

@francescocretti in the meanwhile, is there any specific use case you need help with? If you still need that specific example, I can be found in the `example` folder of this repo: https://github.com/d3plus/d3plus-text/blob/master/example/resizing-text.md

**Comment by francescocretti** [comment]
Hey @davelandry . Thanks for your reply! 

I war trying to use the "auto resize" function. I figured out how to make it work (`.fontResize(true)`).

The example has been helpful, thanks!
