### ISSUE TITLE
Problem with textAnchor?

### ISSUE THREAD

**Issue by jazzido** [d3plus/d3plus-text#3]
Yo @davelandry,

I finally got around to playing with this (awesome work!). I'm trying to add labels to a treemap, but can't get `right` and `left` text anchors to work right. Here's what I get for `textAnchor('left')`:

![screen shot 2016-02-08 at 1 29 32 pm](https://cloud.githubusercontent.com/assets/27584/12894975/1db32992-ce68-11e5-9b24-6b0b03fb1d89.png)

`middle`, OTOH, seems to work OK:

![screen shot 2016-02-08 at 1 29 14 pm](https://cloud.githubusercontent.com/assets/27584/12894978/26671ce2-ce68-11e5-93ef-168294ab829c.png)

[Here's a CodePen that I built for demoing the issue](http://codepen.io/anon/pen/mVQrZx?editors=1010) (scroll all the way to the bottom of the JS, there's a huge blob of data at the top)

Thanks!

**Comment by jazzido** [comment]
Nevermind, I misread the docs. Works perfectly, as the docs clearly state :), with `textAnchor('start')`.

**Comment by davelandry** [comment]
:+1:

I'm trying to keep as close to the SVG standard as I can, so it makes things like this a little confusing.
