### ISSUE TITLE
multiple define functions present when uglifying

### ISSUE THREAD

**Issue by satyakonidala** [d3plus/d3plus-text#40]
Hi you are doing a great job creating this module. But I am unable to use this in my project as it always throws up the error box is undefined. Can you please provide us with some usage examples?

Also I am getting an error saying multiple define functions present when i uglifying my project with the help of grunt and require.js, It would be great if you could help me regarding this.

**Comment by davelandry** [comment]
After updating to today's v0.8 release, please read the Getting Started section of the [README](https://github.com/d3plus/d3plus-text) and discuss any more potential examples here: #2 

If you aren't able to get the uglifying working, please post a stripped down snippit of your code here to help us debug.
