### ISSUE TITLE
long text issue

### ISSUE THREAD

**Issue by geohuz** [d3plus/d3plus-text#53]
I got another issue with the long text rendering,  the rendering text is: "建立客户信息反馈机制，跟踪解决过程，问题解决率达到80%以上", when run with TextBox().overflow(true), throwing the following error:

 d3plus-text.js:210 Uncaught TypeError: Cannot read property 'trimRight' of undefined 

if use with .overflow(false),   the output only includes '...'
I'm using the version 0.9.8

further test shows the issue is related to Chinese symbols, such as '，'  in the above sentance

**Comment by davelandry** [comment]
wasn't able to reproduce the trimRight error, but fixed the full-width comma problem in this commit: https://github.com/d3plus/d3plus-text/commit/86d5f6a6bb44db3656b7005de5c835161e7f4ef3

**Comment by geohuz** [comment]
@davelandry , thanks for fixing it!
