### ISSUE TITLE
double space in textWrap throws off spacing

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-text#55]
@jspeis commented on [Wed Jan 11 2017](https://github.com/d3plus/d3plus-viz/issues/14)

Just noticed this, not sure if I messed up a configuration or something bug thought I would file this in case anyone else encountered a similar issue?

http://codepen.io/jspeis/pen/RKrmPM

Notice that there is a double space "  " after the words "DOUBLE SPACE". If I delete the double space in the title then the spacing in the over words ("Latest Available Data") looks right.

**Comment by davelandry** [comment]
I remember seeing this one with 1.0, I bet it has to do with the textWrap function: https://github.com/d3plus/d3plus-text/blob/master/src/textWrap.js

**Comment by DanLeininger** [comment]
This also happens if there are any `&nbsp;` in the string.  They need to be replaced with regular spaces or words / spacing gets funky.
