### ISSUE TITLE
break line at newline escape character

### ISSUE THREAD

**Issue by demus** [d3plus/d3plus-text#59]
Is this within the scope of the library? something I thought would be useful.

Here is an example use case:

1. text string to split of `string 1\nstring 2`
2.  string 1 &  string 2 will have separate tspan elements  regardless of it they fit on the same line (ellipsis would still show if it overflows too far):

Result:
```
---------------
string 1
string 2
---------------
```

NOT 
```
---------------
string 1 string
 2
---------------
```

**Comment by davelandry** [comment]
Definitely within the scope of the project. Lines should be broken at the `\n` character.
