### ISSUE TITLE
Cannot append d3plus-text word wrap inside d3 code.

### ISSUE THREAD

**Issue by sahaDibyendu** [d3plus/d3plus-text#60]
I am currently using d3plus-text library for text wrapping and dynamic font-size rendering. But somehow it is not getting affected in the chart.

I have the following piece of code:
var paths = markets.append("text")
.text(function(d) { return d.market + ": " + n(d.value);})
                 
                  .attr("x",0)
                  .attr("y", function(d) { return y(d.offset / d.parent.sum)+20; })
                  .each(function(d){
                	  d3plusText.TextBox().select(d3.select(this)).fontsize([8,20])render();
                  }) ;

Please suggest how to append a textbox layer using  d3plus-text inside d3.js.

**Comment by davelandry** [comment]
d3plus-text handles the creation of the "text" element. Check out the getting started example: https://d3plus.org/examples/d3plus-text/getting-started/

If that still doesn't help, please post a jsfiddle of your code so that we can help debug.

**Comment by brandones** [comment]
I've been struggling for about half an hour to figure out how to use d3plus-text. There are no useful examples I could find other than this deleted piece of documentation linked from this issue. For those that find this in the future, [here it is on archive.org](https://web.archive.org/web/20210730050044/https://d3plus.org/examples/d3plus-text/getting-started/). It still works as of this writing:

```js
var data = [
  {text: "Here is <i>some</i> sample text that has been <strong>wrapped</strong> using d3plus.textBox."},
  {text: "...and here is a <b>second</b> sentence!"},
  {text: "这是句3号。这也即使包装没有空格！"}
];

new d3plus.TextBox()
  .data(data)
  .fontSize(16)
  .width(200)
  .x(function(d, i) { return i * 250; })
  .render();
```
