### ISSUE TITLE
Arabic not wrapping on IE11

### ISSUE THREAD

**Issue by Ajdija** [d3plus/d3plus-text#68]
Not working on IE11 + Arabic
http://codepen.io/ajdija/pen/ryoxqe

<img width="926" alt="screen shot 2017-03-31 at 01 13 52" src="https://cloud.githubusercontent.com/assets/7486241/24530015/7f882e6c-15af-11e7-9baf-3d37705ce43e.png">

**Comment by davelandry** [comment]
Fixed in the newest release: https://codepen.io/anon/pen/LjdVWe
