### ISSUE TITLE
TextBox issue?  Some text being given wrong font size.  

### ISSUE THREAD

**Issue by hustontrevor** [d3plus/d3plus-text#73]
### Expected Behavior
It appears that text that does not need to wrap lines is being given the font size of a previous TextBox.

### Current Behavior
![image](https://user-images.githubusercontent.com/33878519/33094471-eb793c54-cec5-11e7-9539-03094a5d3e87.png)

### Steps to Reproduce (for bugs)
http://jsfiddle.net/cjk1g1kr/8/  takes a min to load all the data I'm throwing at it.  

### Your Environment
Chrome, W 7 Pro

It could very possibly be my code.  But I'd appreciate any insight and ideas for a workaround. 
Thanks

**Comment by hustontrevor** [comment]
I think this is strongly linked to the font I'm using.  
Other fonts seem to work better, especially after I double the height/width for the ViewBox.  

Is there a way to make this calculate correctly with a custom font?

**Comment by davelandry** [comment]
Very strange indeed. @hustontrevor would you mind simplifying your example to display only 1 TextBox that sizes incorrectly? It's currently very difficult to tweak the JS in the current jsfiddle.

**Comment by hustontrevor** [comment]
Sorry @davelandry, that was a lot of excess code.
I was able to trim it down to where I still see the issue.  
http://jsfiddle.net/fbed2cp9/

**Comment by davelandry** [comment]
@hustontrevor when rendering fonts on the web, the font specified needs to either be installed on the user's machine or loaded specifically through CSS or a `<link />` tag in the head of the document. Here's an updated fiddle which uses the font "Poppins": http://jsfiddle.net/fbed2cp9/1/
