### ISSUE TITLE
text wrapping for double byte languages

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-text#8]
Google Group: https://groups.google.com/forum/#!topic/d3plus/Mm0f2JW7asg

> Does anyone have experience using the text wrapping functions with double-byte languages like simplified Chinese?   
> 
> I am told they typically don’t use spaces so the wrapping functions do not know where to break and wrap. I get one long (unwrapped) line of characters. 

Is there any way to detect word breaks? How do HTML div containers handle this? Should we just check for breaks between each character?

**Comment by geohuz** [comment]
I thought in Asian Text (such as simplified chinese) we can just split the string based on width limit. The only problem is a paragraph mixed with english text, so we may still need to apply word-wrap for those part.

**Comment by davelandry** [comment]
If that's the case, then it should be too hard to just check/split at each character. Do you know of a regex for detecting non-latin asian characters? This is the function that handles splitting: https://github.com/d3plus/d3plus-text/blob/master/src/split.js#L11-L13

**Comment by geohuz** [comment]
I found a easy way to detect chinese characters, although it is not universally applied to other language:

```
function isChinese(temp)  
{  
 var re = /[^\u4e00-\u9fa5]/;  
 if(re.test(temp)) return false;  
 return true;  
}  
```

**Comment by davelandry** [comment]
Do you mean this works for simplified Chinese, but not, for example, Korean or Japanese?

**Comment by davelandry** [comment]
Just did a little research, it's my current understanding that Korean and Japanese languages do use spaces (please correct me if I'm wrong). So the REGEX we need needs to be able to detect ONLY Chinese characters.

I've set up a little regex playpen for us, starting with what you posted. We need the regex to only identify simplified Chinese characters: https://regex101.com/r/mG5uF8/3

**Comment by geohuz** [comment]
Sorry for the delay, from the regex test I found the previous pattern is not quite correct, and I come up with a new one: https://regex101.com/r/mG5uF8/4 
and I can confirm all the Chinese Characters are matched this time.(You will notice some of the Japanese characters are also being detected and that's true for my knowledge that some Japanese characters are just Chinese. I've also done some research, that Japanese languages don't use spaces just like Chinese, and Korean language use spaces in some cases, but mostly don't use spaces

**Comment by geohuz** [comment]
And I also get the match expression for Korean and Japanese, 

Japanese:

```
\u0800-\u4e00
```

Korean:

```
\u3130-\u318F
\uAC00-\uD7A3
```

and here is the result: https://regex101.com/r/mG5uF8/5

**Comment by davelandry** [comment]
Great work @geohuz! This really jumpstarted me today as I began to dig in.

To the best of my understanding, I was able to get it working for not only Simplified Chinese, but also for Burmese and Lao (which also don't use spaces). Look at the source code here: https://github.com/d3plus/d3plus-text/blob/master/src/split.js

It's a two step process, first, I do the normal split to try and create words from the sentence. I've copied the resulting regex here: https://regex101.com/r/mG5uF8/6

Then, as I look through each word, if the word contains characters from a language without spaces (but not Japanese), it uses the uses the regex seen here: https://regex101.com/r/aE2gB7/1

I ran into a speed bump with Burmese, as it is a language that heavily relies on unicode combining marks (marks that add on to the previous character). I was able to scrape a couple of websites to generate a list of combining marks to look for at the end of all of the words, which can be found here: https://github.com/d3plus/d3plus-text/blob/master/src/combiningMarks.js

If this works for you, I'll close this issue. Also, any regex cleanup/suggestions is highly encouraged 😄

**Comment by geohuz** [comment]
I'm currently using textwrap from d3plus, in a way as such,

```
import d3plus from 'd3plus'

...

      .text(function(d) { return d.val })
      .each(function() {
        d3plus.textwrap()
            .container(d3.select(this))
            .padding(2)
            .valign('middle')
            .size([8,16])
            .resize(true)
            .draw()
      })
```

from the documentation I can't figure out how to use it in a similar way, could you please help me out? 

Thanks!

**Comment by davelandry** [comment]
Hard to write up without seeing your entire code, but the main different is that the new module (in it's current state) needs a data object for each text box and does not infer data from an element already on the page.

``` html
<svg id="container"></svg>
```

``` js
d3plus_text.box()
  .data([{"text": "Label 1"}, {"text": "Label 2"}])
  .fontMax(16)
  .fontMin(8)
  .fontResize(true)
  .select("#container")
  .verticalAlign("middle")
  ()
```

Positioning and sizing occurs with `.x( )` `.y( )` `.width( )` and `.height( )`, either static values for all data points or accessor functions.
