### ISSUE TITLE
Japanese language should be included in noSpaceRange

### ISSUE THREAD

**Issue by t-ohtsuki-cognitee** [d3plus/d3plus-text#96]
Thank you so much for this awesome library!
Without TextBox I would have wasted several days :)
I was a bit confused when I used TextBox with Japanese text,
as the wrapping function seemed to be broken against it.
After looking into the source for a moment, I found the reason:
Japanese too should be included in ``noSpaceRange`` variable in src/textSplit.js !

Typical Japanese texts like "日本語は基本的にはスペースを含みません"  have no space inside them!
See e.g., Japanese Wikipedia article like https://ja.wikipedia.org/wiki/JavaScript.

**Comment by davelandry** [comment]
@t-ohtsuki-cognitee thanks for reaching out and for the kind words! I would love for this library to have better Japanese language support. What is your experience with JavaScript development? I'm a bit swamped with work at the moment, but could make time to review a Pull Request if you can make the necessary changes.

**Comment by t-ohtsuki-cognitee** [comment]
@davelandry  Thanks for such a quick reply!
The fix should be a quite small change so I'll make a PR soon.
